## Traitement de données tabulaires avec une couche dense


In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas

import torch

### 1 : chargement des données 


In [2]:


MyData=pandas.read_csv('notes.csv')
MyData.pop('Eleve')

Matieres=list(MyData.keys())
print(Matieres)

Notes=MyData.to_numpy()
print(Notes)


['Mathematiques', 'Physique', 'Informatique', 'LV1', 'LV2', 'Biologie', 'Chimie']
[[12.6 10.6 14.2 12.3 10.2  9.3  7.7]
 [13.9 12.9 17.9 12.8  8.8 12.  10.9]
 [11.3 10.2 10.6 10.4  5.4  9.4  7. ]
 [10.8 12.2  7.7 13.2  4.8 11.1 10.6]
 [11.8 11.3  9.6 11.7 10.4  9.9  7.6]
 [11.9 11.5 13.9 14.1  8.5  9.3 10.3]
 [11.  11.7 10.1 13.4 13.5  6.3  7.5]
 [10.4  9.2 12.8  6.8  5.1  6.7  7.3]
 [10.1  8.7 11.  16.2 13.2  9.4  6.3]
 [10.2  7.8 13.9 10.   3.6  9.4  8.2]
 [12.2 11.2 12.2 11.7  8.2 10.5  7.8]
 [ 9.8  7.9 13.1 13.4  9.4 11.8  9.2]
 [12.5 11.4 11.2 11.5 13.  10.7  7.4]
 [10.9  8.9 13.8 11.2  9.4 11.9  9.6]
 [10.8  8.2 14.4  9.6  8.8  5.8  5.3]
 [12.9 11.5 14.9 11.9  9.1  9.3  7.9]
 [12.7 14.5 10.2 10.3  8.3  9.6 12.2]
 [13.9 13.1 13.4  9.1  8.7  4.8  4.3]
 [12.2 10.9 13.5 13.3  9.1  6.4  6.4]
 [12.1 11.7 11.8 18.1 17.9  8.9  7.5]
 [13.8 12.7 12.8  9.1  7.9  9.8  8.4]
 [10.6  9.7 13.3 10.8 10.1  8.8 10.3]
 [13.  12.7 11.9 13.   9.   9.   8.1]
 [14.4 13.3 14.7 10.1  7.2  8.6  8.7]
 [11. 

In [3]:
Notes_pt=torch.tensor(Notes,dtype=torch.float64)

print(Notes_pt)

tensor([[12.6000, 10.6000, 14.2000, 12.3000, 10.2000,  9.3000,  7.7000],
        [13.9000, 12.9000, 17.9000, 12.8000,  8.8000, 12.0000, 10.9000],
        [11.3000, 10.2000, 10.6000, 10.4000,  5.4000,  9.4000,  7.0000],
        [10.8000, 12.2000,  7.7000, 13.2000,  4.8000, 11.1000, 10.6000],
        [11.8000, 11.3000,  9.6000, 11.7000, 10.4000,  9.9000,  7.6000],
        [11.9000, 11.5000, 13.9000, 14.1000,  8.5000,  9.3000, 10.3000],
        [11.0000, 11.7000, 10.1000, 13.4000, 13.5000,  6.3000,  7.5000],
        [10.4000,  9.2000, 12.8000,  6.8000,  5.1000,  6.7000,  7.3000],
        [10.1000,  8.7000, 11.0000, 16.2000, 13.2000,  9.4000,  6.3000],
        [10.2000,  7.8000, 13.9000, 10.0000,  3.6000,  9.4000,  8.2000],
        [12.2000, 11.2000, 12.2000, 11.7000,  8.2000, 10.5000,  7.8000],
        [ 9.8000,  7.9000, 13.1000, 13.4000,  9.4000, 11.8000,  9.2000],
        [12.5000, 11.4000, 11.2000, 11.5000, 13.0000, 10.7000,  7.4000],
        [10.9000,  8.9000, 13.8000, 11.2000,  9.400

### 2 : somme pondérée des données 


In [4]:

lin_filter=torch.nn.Linear(7, 1, bias=False)

wgt=1./7.

lin_filter.weight.data = torch.tensor([[wgt,wgt,wgt,wgt,wgt,wgt,wgt]],dtype=torch.float64)

filtered_data=lin_filter(Notes_pt)

print(filtered_data)


tensor([[10.9857],
        [12.7429],
        [ 9.1857],
        [10.0571],
        [10.3286],
        [11.3571],
        [10.5000],
        [ 8.3286],
        [10.7000],
        [ 9.0143],
        [10.5429],
        [10.6571],
        [11.1000],
        [10.8143],
        [ 8.9857],
        [11.0714],
        [11.1143],
        [ 9.6143],
        [10.2571],
        [12.5714],
        [10.6429],
        [10.5143],
        [10.9571],
        [11.0000],
        [10.7857],
        [10.6857],
        [10.0714],
        [12.7714],
        [11.4000]], dtype=torch.float64, grad_fn=<MmBackward>)


In [5]:
lin_filter=torch.nn.Linear(7, 1, bias=False)

lin_filter.weight.data = torch.tensor([[0.2,0.2,0.2,0,0,0.2,0.2]],dtype=torch.float64)

filtered_data=lin_filter(Notes_pt[:10,:])

print(filtered_data)


tensor([[10.8800],
        [13.5200],
        [ 9.7000],
        [10.4800],
        [10.0400],
        [11.3800],
        [ 9.3200],
        [ 9.2800],
        [ 9.1000],
        [ 9.9000]], dtype=torch.float64, grad_fn=<MmBackward>)


In [6]:
lin_filter=torch.nn.Linear(7, 1, bias=False)

lin_filter.weight.data = torch.tensor([[0.0,0.0,0.0,0.5,0.5,0.0,0.0]],dtype=torch.float64)

filtered_data=lin_filter(Notes_pt[:10,:])

print(filtered_data)

tensor([[11.2500],
        [10.8000],
        [ 7.9000],
        [ 9.0000],
        [11.0500],
        [11.3000],
        [13.4500],
        [ 5.9500],
        [14.7000],
        [ 6.8000]], dtype=torch.float64, grad_fn=<MmBackward>)


In [7]:
lin_filter=torch.nn.Linear(7, 1, bias=False)

lin_filter.weight.data = torch.tensor([[1.0,0.0,-1.0,0.0,0.0,0.0,0.0]],dtype=torch.float64)

filtered_data=lin_filter(Notes_pt[:10,:])

print(filtered_data)

tensor([[-1.6000],
        [-4.0000],
        [ 0.7000],
        [ 3.1000],
        [ 2.2000],
        [-2.0000],
        [ 0.9000],
        [-2.4000],
        [-0.9000],
        [-3.7000]], dtype=torch.float64, grad_fn=<MmBackward>)


### 3 : somme pondérée des données avec biais puis ReLU 

In [8]:
lin_filter=torch.nn.Linear(7, 1, bias=True)

lin_filter.weight.data = torch.tensor([[0.2,0.2,0.2,0,0,0.2,0.2]],dtype=torch.float64)

lin_filter.bias.data = torch.tensor([-10],dtype=torch.float64)


filtered_data=lin_filter(Notes_pt[:10,:])

print(filtered_data)

tensor([[ 0.8800],
        [ 3.5200],
        [-0.3000],
        [ 0.4800],
        [ 0.0400],
        [ 1.3800],
        [-0.6800],
        [-0.7200],
        [-0.9000],
        [-0.1000]], dtype=torch.float64, grad_fn=<AddmmBackward>)


In [9]:
act_func_relu=torch.nn.ReLU()

lin_filter=torch.nn.Linear(7, 1, bias=True)

lin_filter.weight.data = torch.tensor([[0.2,0.2,0.2,0,0,0.2,0.2]],dtype=torch.float64)

lin_filter.bias.data = torch.tensor([-10],dtype=torch.float64)


filtered_data=act_func_relu(lin_filter(Notes_pt[:10,:]))

print(filtered_data)

tensor([[0.8800],
        [3.5200],
        [0.0000],
        [0.4800],
        [0.0400],
        [1.3800],
        [0.0000],
        [0.0000],
        [0.0000],
        [0.0000]], dtype=torch.float64, grad_fn=<ReluBackward0>)


In [12]:
#definition de la fonction d'activation ReLU
act_func_relu=torch.nn.ReLU()

#definition de la couche dense et de ses parametres 
lin_filter=torch.nn.Linear(7, 2, bias=True)

lin_filter.weight.data = torch.tensor([[0.2,0.2,0.2,0,0,0.2,0.2],
                                       [0.0,0.0,0.0,0.5,0.5,0.,0.]],
                                      dtype=torch.float64)

lin_filter.bias.data = torch.tensor([-10,-10],dtype=torch.float64)


#traitement des données 
filtered_data=act_func_relu(lin_filter(Notes_pt[:,:]))

#résultat 
print(filtered_data)

tensor([[0.8800, 1.2500],
        [3.5200, 0.8000],
        [0.0000, 0.0000],
        [0.4800, 0.0000],
        [0.0400, 1.0500],
        [1.3800, 1.3000],
        [0.0000, 3.4500],
        [0.0000, 0.0000],
        [0.0000, 4.7000],
        [0.0000, 0.0000],
        [0.7800, 0.0000],
        [0.3600, 1.4000],
        [0.6400, 2.2500],
        [1.0200, 0.3000],
        [0.0000, 0.0000],
        [1.3000, 0.5000],
        [1.8400, 0.0000],
        [0.0000, 0.0000],
        [0.0000, 1.2000],
        [0.4000, 8.0000],
        [1.5000, 0.0000],
        [0.5400, 0.4500],
        [0.9400, 1.0000],
        [1.9400, 0.0000],
        [0.2200, 2.2000],
        [0.0600, 2.2500],
        [0.4000, 0.0000],
        [2.9800, 2.2500],
        [1.2400, 1.8000]], dtype=torch.float64, grad_fn=<ReluBackward0>)
